version: '3.9'

networks:
  monitoring:
    driver: bridge

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env
    volumes:
      - ./inputFile:/csvserver/inputdata
    networks:
      - monitoring
    restart: unless-stopped

# Prometheus and grafana